spring:
  application:
    name: crowdtrace-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cors:
  allowed-origins:
    - "https://crowdtrace.com"
    - "https://www.crowdtrace.com"
    - "https://*.crowdtrace.com"

server:
  port: 8080

resend:
  url: "https://api.resend.com/emails"
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}
