spring:
  application:
    name: crowdtrace-backend
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

logging:
  structured:
    format:
      console: ecs
