-- Case registry schema (CT-011).
--
-- Four tables with one privacy boundary: `cases` holds what may become public plus the
-- admin-only review signals; `case_sensitive_details` holds admin-only personal data and is
-- deleted as a whole by retention cleanup, which is why reporter_relationship can stay
-- NOT NULL. Files and consents name the user who created them so every record is
-- attributable. Lifecycle transitions are enforced by the case services, not here — the
-- checks below only pin the vocabulary and the two states that can never be valid.

CREATE TABLE cases
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporter_id           BIGINT                      NOT NULL,
    full_name             VARCHAR(255)                NOT NULL,
    age                   SMALLINT                    NOT NULL,
    gender                VARCHAR(32)                 NOT NULL,
    last_seen_date        DATE                        NOT NULL,
    region                VARCHAR(32)                 NOT NULL,
    last_seen_location    VARCHAR(500)                NOT NULL,
    physical_description  TEXT                        NOT NULL,
    clothing              TEXT                        NOT NULL,
    circumstances         TEXT                        NOT NULL,
    public_contact_number VARCHAR(32)                 NOT NULL,
    review_status         VARCHAR(32)                 NOT NULL,
    case_status           VARCHAR(32),
    closing_statement     TEXT,
    priority_minor        BOOLEAN                     NOT NULL DEFAULT FALSE,
    duplicate_flag        BOOLEAN                     NOT NULL DEFAULT FALSE,
    version               BIGINT                      NOT NULL DEFAULT 0,
    submitted_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    approved_at           TIMESTAMP WITHOUT TIME ZONE,
    resolved_at           TIMESTAMP WITHOUT TIME ZONE,
    closed_at             TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cases PRIMARY KEY (id),
    -- RESTRICT: users are soft-deleted (V4). A hard delete must not orphan a case.
    CONSTRAINT fk_cases_reporter FOREIGN KEY (reporter_id) REFERENCES users (id),
    CONSTRAINT cases_age_check CHECK (age BETWEEN 0 AND 130),
    CONSTRAINT cases_gender_check CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT cases_region_check CHECK (region IN (
        'AHAFO', 'ASHANTI', 'BONO', 'BONO_EAST', 'CENTRAL', 'EASTERN', 'GREATER_ACCRA',
        'NORTH_EAST', 'NORTHERN', 'OTI', 'SAVANNAH', 'UPPER_EAST', 'UPPER_WEST', 'VOLTA',
        'WESTERN', 'WESTERN_NORTH')),
    CONSTRAINT cases_review_status_check CHECK (review_status IN (
        'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'TAKEN_DOWN')),
    CONSTRAINT cases_case_status_check CHECK (case_status IN (
        'MISSING', 'FOUND_SAFE', 'FOUND_DECEASED', 'CLOSED')),
    -- A published case always has a public outcome; a never-published case never has one.
    -- TAKEN_DOWN is deliberately unconstrained: it may keep the outcome it had while live.
    CONSTRAINT cases_approved_has_outcome_check
        CHECK (review_status <> 'APPROVED' OR case_status IS NOT NULL),
    CONSTRAINT cases_unpublished_has_no_outcome_check
        CHECK (review_status NOT IN ('SUBMITTED', 'UNDER_REVIEW', 'REJECTED') OR case_status IS NULL)
);

-- "My cases" for a reporter, newest first.
CREATE INDEX idx_cases_reporter ON cases (reporter_id, created_at DESC);
-- Moderation queue: minors first, then oldest submission (PRD §3.5, US-02).
CREATE INDEX idx_cases_review_queue ON cases (review_status, priority_minor DESC, submitted_at);
-- Public registry filters by outcome among published cases only.
CREATE INDEX idx_cases_public_status ON cases (case_status) WHERE review_status = 'APPROVED';

CREATE TABLE case_sensitive_details
(
    case_id               BIGINT                      NOT NULL,
    reporter_relationship VARCHAR(100)                NOT NULL,
    medical_conditions    TEXT,
    known_associates      TEXT,
    vehicle_info          TEXT,
    social_media_handles  TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_case_sensitive_details PRIMARY KEY (case_id),
    CONSTRAINT fk_case_sensitive_details_case FOREIGN KEY (case_id) REFERENCES cases (id) ON DELETE CASCADE
);

-- case_id is NULL between upload and submission (CT-015 → CT-013); uploaded_by is never NULL.
CREATE TABLE case_files
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id         BIGINT,
    uploaded_by     BIGINT                      NOT NULL,
    purpose         VARCHAR(32)                 NOT NULL,
    visibility      VARCHAR(32)                 NOT NULL,
    storage_key     VARCHAR(512)                NOT NULL,
    content_type    VARCHAR(100)                NOT NULL,
    size_bytes      BIGINT                      NOT NULL,
    checksum_sha256 CHAR(64)                    NOT NULL,
    uploaded_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    attached_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_case_files PRIMARY KEY (id),
    CONSTRAINT fk_case_files_case FOREIGN KEY (case_id) REFERENCES cases (id),
    CONSTRAINT fk_case_files_uploader FOREIGN KEY (uploaded_by) REFERENCES users (id),
    CONSTRAINT case_files_purpose_check CHECK (purpose IN ('REPORT', 'PHOTO')),
    CONSTRAINT case_files_visibility_check CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
    -- A police report can never be stored as public; a photo is always publishable.
    CONSTRAINT case_files_purpose_visibility_check CHECK (
        (purpose = 'REPORT' AND visibility = 'PRIVATE') OR (purpose = 'PHOTO' AND visibility = 'PUBLIC')),
    CONSTRAINT case_files_size_check CHECK (size_bytes > 0),
    CONSTRAINT case_files_attachment_check CHECK ((case_id IS NULL) = (attached_at IS NULL))
);

CREATE UNIQUE INDEX uq_case_files_storage_key ON case_files (storage_key);
CREATE INDEX idx_case_files_case ON case_files (case_id, purpose) WHERE deleted_at IS NULL;
-- Stale-upload cleanup and "my pending uploads".
CREATE INDEX idx_case_files_unattached ON case_files (uploaded_by, uploaded_at) WHERE case_id IS NULL;

-- Append-only. A new policy version is a new row; the same version twice is a bug.
CREATE TABLE case_consents
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id         BIGINT                      NOT NULL,
    user_id         BIGINT                      NOT NULL,
    consent_type    VARCHAR(32)                 NOT NULL,
    consent_version VARCHAR(32)                 NOT NULL,
    source          VARCHAR(32)                 NOT NULL,
    accepted_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_case_consents PRIMARY KEY (id),
    CONSTRAINT fk_case_consents_case FOREIGN KEY (case_id) REFERENCES cases (id),
    CONSTRAINT fk_case_consents_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT case_consents_type_check CHECK (consent_type IN ('SENSITIVE_DATA_COLLECTION')),
    CONSTRAINT case_consents_source_check CHECK (source IN ('WEB', 'MOBILE', 'API')),
    CONSTRAINT uq_case_consents_version UNIQUE (case_id, consent_type, consent_version)
);

CREATE INDEX idx_case_consents_case ON case_consents (case_id, accepted_at);
CREATE INDEX idx_case_consents_user ON case_consents (user_id);
