CREATE TABLE case_duplicate_matches
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id           BIGINT NOT NULL REFERENCES cases (id),
    matched_case_id   BIGINT NOT NULL REFERENCES cases (id),
    confidence        SMALLINT NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    name_similarity   SMALLINT NOT NULL CHECK (name_similarity BETWEEN 0 AND 1000),
    day_difference    SMALLINT NOT NULL CHECK (day_difference >= 0),
    reasons           VARCHAR(200) NOT NULL,
    algorithm_version VARCHAR(16) NOT NULL,
    detected_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_case_duplicate_matches_pair UNIQUE (case_id, matched_case_id),
    CONSTRAINT case_duplicate_matches_not_self CHECK (case_id <> matched_case_id)
);

CREATE INDEX idx_case_duplicate_matches_matched_case ON case_duplicate_matches (matched_case_id);
CREATE INDEX idx_cases_last_seen ON cases (last_seen_date, id);
