-- Human review history, security audit events, and user-submitted content reports.
-- Lifecycle rules owned by application services remain outside this schema.

CREATE TABLE case_reviews
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id      BIGINT                      NOT NULL,
    reviewer_id  BIGINT                      NOT NULL,
    decision     VARCHAR(32)                 NOT NULL,
    review_source VARCHAR(32)                 NOT NULL,
    review_notes VARCHAR(2000),
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_case_reviews PRIMARY KEY (id),
    CONSTRAINT fk_case_reviews_case FOREIGN KEY (case_id) REFERENCES cases (id),
    CONSTRAINT fk_case_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (id),
    CONSTRAINT case_reviews_decision_check CHECK (decision IN ('APPROVED', 'REJECTED')),
    CONSTRAINT case_reviews_source_check CHECK (review_source = 'HUMAN'),
    CONSTRAINT case_reviews_rejection_notes_check CHECK (
        decision <> 'REJECTED' OR (review_notes IS NOT NULL AND btrim(review_notes) <> ''))
);

CREATE INDEX idx_case_reviews_case ON case_reviews (case_id, created_at, id);
CREATE INDEX idx_case_reviews_reviewer ON case_reviews (reviewer_id, created_at, id);
-- The review queue remains on the existing cases review-queue index.

CREATE TABLE audit_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id       BIGINT,
    actor_role     VARCHAR(32)                 NOT NULL,
    action         VARCHAR(64)                 NOT NULL,
    target_type    VARCHAR(32)                 NOT NULL,
    target_id      BIGINT                      NOT NULL,
    metadata       JSONB                       NOT NULL DEFAULT '{}'::jsonb,
    correlation_id VARCHAR(64),
    occurred_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_events PRIMARY KEY (id),
    CONSTRAINT fk_audit_events_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT audit_events_actor_role_check CHECK (
        actor_role IN ('REGISTERED_USER', 'MODERATOR', 'SUPER_ADMIN', 'SYSTEM')),
    -- A system event has no user actor; every other event names its user actor.
    CONSTRAINT audit_events_system_actor_check CHECK ((actor_id IS NULL) = (actor_role = 'SYSTEM')),
    CONSTRAINT audit_events_action_format_check CHECK (
        action ~ '^[A-Z][A-Z0-9_]*(\.[A-Z][A-Z0-9_]*)*$'),
    CONSTRAINT audit_events_target_type_format_check CHECK (
        target_type ~ '^[A-Z][A-Z0-9_]*(\.[A-Z][A-Z0-9_]*)*$'),
    CONSTRAINT audit_events_metadata_object_check CHECK (jsonb_typeof(metadata) = 'object'),
    -- Metadata shape and size are schema-owned; allowed keys and redaction are CT-020 policy.
    CONSTRAINT audit_events_metadata_size_check CHECK (octet_length(metadata::text) <= 4096)
);

CREATE INDEX idx_audit_events_target ON audit_events (target_type, target_id, occurred_at, id);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_id, occurred_at, id) WHERE actor_id IS NOT NULL;
CREATE INDEX idx_audit_events_action ON audit_events (action, occurred_at, id);
CREATE INDEX idx_audit_events_occurred ON audit_events (occurred_at, id);

CREATE TABLE content_reports
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    -- CT-025 creates comments; this intentionally has no FK until then.
    comment_id       BIGINT                      NOT NULL,
    reporter_id      BIGINT                      NOT NULL,
    reason           VARCHAR(32)                 NOT NULL,
    details          VARCHAR(1000),
    status           VARCHAR(32)                 NOT NULL DEFAULT 'OPEN',
    resolution       VARCHAR(32),
    moderator_id     BIGINT,
    resolution_notes VARCHAR(2000),
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_content_reports PRIMARY KEY (id),
    CONSTRAINT fk_content_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id),
    CONSTRAINT fk_content_reports_moderator FOREIGN KEY (moderator_id) REFERENCES users (id),
    CONSTRAINT content_reports_reason_check CHECK (
        reason IN ('SPAM', 'HARASSMENT', 'MISINFORMATION', 'PRIVACY', 'OTHER')),
    CONSTRAINT content_reports_other_details_check CHECK (
        reason <> 'OTHER' OR (details IS NOT NULL AND btrim(details) <> '')),
    CONSTRAINT content_reports_status_check CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT content_reports_resolution_check CHECK (resolution IN ('REMOVED', 'DISMISSED')),
    CONSTRAINT content_reports_attribution_check CHECK (
        (status = 'OPEN' AND resolution IS NULL AND moderator_id IS NULL
            AND resolution_notes IS NULL AND resolved_at IS NULL)
        OR (status = 'RESOLVED' AND resolution IS NOT NULL
            AND moderator_id IS NOT NULL AND resolved_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_content_reports_open_reporter
    ON content_reports (comment_id, reporter_id) WHERE status = 'OPEN';
CREATE INDEX idx_content_reports_open_queue ON content_reports (created_at, id) WHERE status = 'OPEN';
CREATE INDEX idx_content_reports_open_comment ON content_reports (comment_id) WHERE status = 'OPEN';
CREATE INDEX idx_content_reports_reporter ON content_reports (reporter_id);
