CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255)                            NOT NULL,
    last_name       VARCHAR(255)                            NOT NULL,
    username        VARCHAR(255)                            NOT NULL,
    display_name    VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    password        VARCHAR(255)                            NOT NULL,
    role            VARCHAR(255)                            NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    profile_picture VARCHAR(255),
    phone_number    VARCHAR(255),
    bio             VARCHAR(255),
    postcount       INTEGER                                 NOT NULL,
    is_verified     BOOLEAN                                 NOT NULL,
    is_enabled      BOOLEAN                                 NOT NULL,
    is_deleted      BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);