CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    password_hash  VARCHAR(255)                            NOT NULL,
    display_name   VARCHAR(255)                            NOT NULL,
    role           VARCHAR(32)                             NOT NULL,
    account_status VARCHAR(32)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_role ON users (role);

CREATE TABLE verification_requests
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                 NOT NULL,
    verification_type  VARCHAR(32)                            NOT NULL,
    evidence_reference VARCHAR(1024)                          NOT NULL,
    status             VARCHAR(32)                            NOT NULL,
    reviewer_id        BIGINT,
    review_notes       VARCHAR(2000),
    created_at         TIMESTAMP WITHOUT TIME ZONE            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verification_requests PRIMARY KEY (id),
    CONSTRAINT fk_verification_requests_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_verification_requests_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES users (id)
);

CREATE INDEX idx_verification_requests_user ON verification_requests (user_id);
CREATE INDEX idx_verification_requests_queue
    ON verification_requests (status, created_at);
