CREATE TABLE revoked_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(64)                              NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_revoked_tokens PRIMARY KEY (id),
    CONSTRAINT uc_revoked_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_revoked_tokens_expires_at ON revoked_tokens (expires_at);
